ALTER TABLE operaciones DISABLE TRIGGER ALL;
ALTER TABLE saldos DISABLE TRIGGER ALL;

TRUNCATE TABLE operaciones, saldos RESTART IDENTITY CASCADE;

ALTER TABLE operaciones ENABLE TRIGGER ALL;
ALTER TABLE saldos ENABLE TRIGGER ALL;

UPDATE caja
SET saldocaja = 0.00,
    saldocomision = 0.00;
